### ISSUE TITLE
Inconsistent NaN behavior

### ISSUE THREAD

**Issue by chaburkland** [brandtbucher/automap#8] opened 2022-02-16 23:46 UTC
```python
from automap import FrozenAutoMap

FrozenAutoMap((float("nan") for _ in range(3)))       # This works!
FrozenAutoMap((np.float64("nan") for _ in range(3)))  # This works!
FrozenAutoMap((np.nan for _ in range(3)))             # This fails!
```

**Comment by brandtbucher** [comment] 2022-02-17 00:11
Pretty sure this is a duplicate of #5. Note that these lines are not doing the same thing, and `automap`'s behavior is consistent with Python's built-in hash table types:

```py
>>> {float("nan") for _ in range(3)}
{nan, nan, nan}
>>> {np.float64("nan") for _ in range(3)}
{nan, nan, nan}
>>> {np.nan for _ in range(3)}
{nan}
```

(Feel free to reopen if I missed something!)

**Closed by brandtbucher** 2022-02-17 00:11 UTC
